services:
  app:
    image: carpentry-img
    environment:
       DB_CONNECTION: ${DB_CONNECTION}
       ASPNETCORE_URLS: ${ASPNETCORE_URLS}
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "8080:5000"
    # depends_on:
      # - db
